name: 02-workflow-events
on: 
    # push:
    # pull_request:
    # schedule:
    #     - cron: '*/10 * * * *'
        # runs every 10 mins
    workflow_dispatch:
        # workflow dispatch allows us to trigger the workflow from the UI
        # Run echo "i've been triggered by a(n) workflow_dispatch event."
        # i've been triggered by a(n) workflow_dispatch event.

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "i've been triggered by a(n) ${{github.event_name}} event."
            #   accessing the events using ${{}}
