name: 03-workflow-runners
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: | #indicates a multiline bash script is about to come
                echo "this job is running on an ubuntu runner."
                echo "Runner OS: $RUNNER_OS" 
