name: 03-workflow-runners
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: | #indicates a multiline bash script is about to come
                echo "this job is running on an ubuntu runner."
                echo "Runner OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: show os
              shell: bash #note we have to include the shell type only for window so that it can understand $RUNNER_OS
              run: | 
                echo "this job is running on a windows runner."
                echo "Runner os: $RUNNER_OS"
    mac-os:
        runs-on: mac-latest
        steps:
          - name: mac os
            run: |
              echo "this job is running on a mac runner"
              echo "Runner os: $RUNNER_OS"
               
