name: 04-using-actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: printing folders
              run: ls
            - name: setup node 
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: install dependencies
              run:
                # cd  04-using-actions/react-app
                npm ci #npm clean install
              #working-directory: 04-using-actions/react-app #working directory sets the directory in which to run the actions. beacuse the npm clean install commands requires some packages which is not there in teh root directory but inside the 04-using-actions-react-app
            - name: run unit tests
              run: npm run test #in the package .json there is somethings called as scripts which has certain commands for a react application to run. one amoung which is this run test.
              #working-directory: 04-using-actions/react-app
            # 1. checkout the code from the repository
            # 2. install dependencies for out raect application 
            # 3. execute automated tests
            
