name: 05-1-filters-activity-type
on:
    pull_request:
        types:
            - opened
            - synchronize
        branches: 
            - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "running whenever a PR is opened or synchronised and base branch is main"

            